#for develop
version: "3"
services:
    whoamiapi:
        build: .
        network_mode: host
        environment:
            - PORT=5000
            - DB_NAME=whoami
            - DB_USER=whoami
            - DB_PASS=wh04m1
            - DB_HOST=localhost
            - DB_PORT=5432
        volumes:
            - ".:/app"