FROM node:10-alpine as build-step
RUN apk add git &&\
    mkdir -p /app
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . .
RUN npm run build
FROM node:10-alpine
COPY --from=build-step /app/dist /usr/src
COPY --from=build-step /app/node_modules /usr/src/node_modules
WORKDIR /usr/src
RUN ls
CMD node api.js